### PR TITLE
Upgrade to Slinky 0.3.0

### PR DESCRIPTION
**Pull request by matthewpflueger**

### CODE REVIEW

**Comment by matthewpflueger** [comment]
@shadaj this doesn't compile yet due to DataComponent extending ExternalComponent and the failure of the ExternalPropsWriterProvider macro expansion. I see there needs to be an implicit ExternalPropsWriterProvider but for the life of me I can't seem to make out how to provide that. Any suggestions?

**Comment by shadaj** [comment]
@matthewpflueger so the purpose of `ExternalPropsWriterProvider` is to grab the implicit `Writer` during the creation of the `ExternalComponent` object so that we can reuse it for each call to `apply`. The macro in this case is (incorrectly) assuming that the external component is an object, leading to the expansion failure.

In any case, the macro is designed to work only when the complete `Props` type is known, but in this case with the type parameter it is not. To get things to compile in this case, we need to take the extra props `Writer` as an implicit parameter and cast it to `ExternalPropsWriterProvider` to satisfy the implicit parameters of `ExternalComponent`. So something like this:
```scala
class DataComponent[P <: ApolloProps](comp: js.Object)(implicit extraPropsWriter: Writer[P#ExtraProps])
  extends ExternalComponent()(extraPropsWriter.asInstanceOf[ExternalPropsWriterProvider]) {
```

**Comment by matthewpflueger** [comment]
Okay, that worked! Thanks a lot! Weirdly the example/compile:doc is failing for every component in the example with type mismatch like when I publishLocal:

```
[error] react-apollo-scalajs/example/src/main/scala/com/apollographql/scalajs/AuthorView.scala:25: type mismatch;
[error]  found   : com.apollographql.scalajs.AuthorView.type
[error]  required: slinky.core.BaseComponentWrapper{type Props = com.apollographql.scalajs.ApolloQueryProps[com.apollographql.scalajs.AuthorQuery.Data,com.apollographql.scalajs.AuthorView.ExtraProps]}
[error]   )((e: AuthorView.ExtraProps) => Some(AuthorQuery.Variables(e.id)))(this)
[error]                                                                      ^
```

Could this be macro expansion issue? The code itself gets published just fine...

**Comment by shadaj** [comment]
Hmm, I'm not sure what's going on. I'm going to merge the changes for now so they can get published, but will investigate soon.

**Pull request merged**
