### PR TITLE
WIP Update to slinky 0.2.0

### PR DESCRIPTION
**Pull request by matthewpflueger**

### CODE REVIEW

**Comment by matthewpflueger** [comment]
Hi, this is the initial work to update to Slinky 0.2.0. Let me know if I am on the right track. Happy to continue working on this if you like the direction...

**Comment by shadaj** [comment]
@matthewpflueger this looks awesome! All the changes look good, have you been able to test with a local application? If not, I can also test it on my own apps.

**Comment by matthewpflueger** [comment]
I have tested with my local application. It works using the old style components (using ComponentWrapper) but I need a pointer how to convert to the new style (using the @react macro).

**Comment by matthewpflueger** [comment]
@shadaj Hi, I am really having trouble converting the example components to use the react macro. Basically the graphql methods need a component that is a BaseComponentWrapper but what we have is a Component. I know the macro transforms the component to extend ComponentWrapper but I am at a loss as to how to use that with the graphql methods... Any pointers?

**Comment by shadaj** [comment]
@matthewpflueger when the macro annotation runs, it generates a companion object that extends `BaseComponentWrapper`. So if you add `val WithData = graphql(MyQuery)(this)` inside the companion object of the macro annotated component, everything should work.

**Comment by matthewpflueger** [comment]
Yeah, that is what I tried first and I'm getting the following errors:

```bash
[error] <macro>:8: type mismatch;
[error]  found   : UpVote.this.type (with underlying type com.apollographql.scalajs.UpVote)
[error]  required: me.shadaj.slinky.core.BaseComponentWrapper{type Props = com.apollographql.scalajs.ApolloMutationProps[com.apollographql.scalajs.UpVoteMutation.Variables,com.apollographql.scalajs.UpVoteMutation.Data,?]}
[error]     val WithData = graphql(UpVoteMutation)(this)
[error]                                            ^
[error] <macro>:16: type mismatch;
[error]  found   : Def.this.type (with underlying type com.apollographql.scalajs.UpVote.Def)
[error]  required: me.shadaj.slinky.core.BaseComponentWrapper{type Props = com.apollographql.scalajs.ApolloMutationProps[com.apollographql.scalajs.UpVoteMutation.Variables,com.apollographql.scalajs.UpVoteMutation.Data,?]}
[error]       val WithData = graphql(UpVoteMutation)(this)
[error]                                              ^
[error] two errors found
[error] (example/compile:compileIncremental) Compilation failed
```

This is what I changed UpVote to (commenting out the render for simplification):

```scala
case class ExtraProps(postId: Int, update: UpVoteMutation.Data => Unit)
@react class UpVote extends Component {
  type Props = UpVoteMutation.Props#WithExtra[ExtraProps]
  type State = Boolean

  def initialState = false

  def render(): ReactElement = {
    div("test")
//    button(onClick := (() => {
//      setState(true)
//      props.mutate(UpVoteMutation.Variables(props.extraProps.postId)).foreach { r =>
//        setState(false)
//        props.extraProps.update(r)
//      }
//    }), disabled := state)(
//      div(if (state) "upvoting" else "upvote!")
//    )
  }

  val WithData = graphql(UpVoteMutation)(this)
}
```

**Comment by shadaj** [comment]
So the `val WithData = graphql(UpVoteMutation)(this)` needs to go in an `object UpVote` companion to the annotated class. That way, `this` is referring to the wrapper, not the definition class.

**Comment by matthewpflueger** [comment]
Yes, I tried that too. Is it working for you? I feel like I am going crazy.  This is what I have now:

```scala
case class ExtraProps(postId: Int, update: UpVoteMutation.Data => Unit)
@react class UpVote extends Component {
  type Props = UpVoteMutation.Props#WithExtra[ExtraProps]
  type State = Boolean

  override def initialState = false

  override def render(): ReactElement = {
    div("test")
  }
}

object UpVote {
  val WithData = graphql(UpVoteMutation)(this)
}
```

And I receive this error:

```sh
[error] /opt/matthewpflueger/react-apollo-scalajs/example/src/main/scala/com/apollographql/scalajs/UpVote.scala:22: type mismatch;
[error]  found   : com.apollographql.scalajs.UpVote.type
[error]  required: me.shadaj.slinky.core.BaseComponentWrapper{type Props = com.apollographql.scalajs.ApolloMutationProps[com.apollographql.scalajs.UpVoteMutation.Variables,com.apollographql.scalajs.UpVoteMutation.Data,?]}
[error]   val WithData = graphql(UpVoteMutation)(this)
[error]                                          ^
[error] one error found
```

**Comment by shadaj** [comment]
Figured it out! The macro paradise plugin was missing, so the annotation was never expanded. If you add `addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M11" cross CrossVersion.full)` to `example/build.sbt`, the component compiles!

**Comment by matthewpflueger** [comment]
Ugh, I am an idiot. I could have sworn the compiler plugin was there already. Usually, I receive an error saying the macro can't expand which wasn't the case this time. Anyway, sorry for wasting your time. The latest commit converts the example components to the new style and compiles without warnings. I haven't tested though...

**Comment by shadaj** [comment]
Hmm, I think the compiler error not showing up might be a bug in Slinky itself. I'll take a look to see if that can be fixed.

**Comment by matthewpflueger** [comment]
Cool. Well, let me know if there is anything else that needs to be done to get this PR merged. Otherwise, I think it is good to go...

**Pull request merged**
